// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ID                 string             `json:"id"`
	Name               *string            `json:"name,omitempty"`
	MessagesConnection *MessageConnection `json:"messagesConnection,omitempty"`
}

type ChannelInput struct {
	Name string `json:"name"`
}

type Message struct {
	ID      string `json:"id"`
	Content string `json:"content"`
	User    string `json:"user"`
	Date    string `json:"date"`
}

type MessageConnection struct {
	Edges    []*MessageEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type MessageEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Message `json:"node"`
}

type MessageInput struct {
	Content string `json:"content"`
	User    string `json:"user"`
	Date    string `json:"date"`
}

type Mutation struct {
}

type PageInfo struct {
	StartCursor string `json:"startCursor"`
	EndCursor   string `json:"endCursor"`
	HasNextPage bool   `json:"HasNextPage"`
}

type Query struct {
}

type Subscription struct {
}
