// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ID       string     `json:"id"`
	Name     *string    `json:"name,omitempty"`
	Messages []*Message `json:"messages"`
}

type ChannelInput struct {
	Name string `json:"name"`
}

type Message struct {
	ID        string   `json:"id"`
	Content   string   `json:"content"`
	User      string   `json:"user"`
	Date      string   `json:"date"`
	Channel   *Channel `json:"channel"`
	ChannelID int      `json:"channelId"`
}

type MessageInput struct {
	Content   string `json:"content"`
	User      string `json:"user"`
	Date      string `json:"date"`
	ChannelID int    `json:"channelId"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}
